name: Build and Deploy Portfolio Solution to Google Cloud Platform

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0'

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build API and Client
        run: |
          dotnet publish MyPortfolioSolution/MyPortfolioApi -c Release -o production
          cd MyPortfolioSolution/MyPortfolioClient
          npm ci
          npm run build
          cp -rT dist ../..//production/dist

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --set-env-vars=PORT=5000
