name: Build and Push Portfolio Solution to Google Cloud Platform
on:
  push:
    branches: [master]


jobs:
  clean-old-production:
    name: Delete production directory content
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deleting old files
      run: rm -rf production/
    - name: Create produciton directory
      run: |- 
        mkdir production
        ls



  build-dotnet:
    needs: clean-old-production
    name: Build Dotnet Api
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0'

    - name: Build
      run: |
        cd MyPortfolioSolution/MyPortfolioApi
        dotnet publish -c Release 

    - name: Move Api files to production directory
      run: |
        pwd
        ls
        cp -a MyPortfolioSolution/MyPortfolioApi/bin/Release/net6.0/publish/. /production/
                                

  build-vue:
    needs: clean-old-production
    name: Build Vue Client
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: npm install & build
      run: |
        cd MyPortfolioSolution/MyPortfolioClient
        npm install
        npm run build 

    - name: Move Client dist to production directory
      run: |
        pwd
        ls
        cp -a MyPortfolioSolution/MyPortfolioClient/dist/ /production/

  
  build-push-gcr:
    needs: [build-dotnet, build-vue] 
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: myportfolio
      PROJECT_ID: portfolio-5fc05
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
      
    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG


    - name: Push Docker Image to Artifact Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG



        